# Generated by Django 4.1.3 on 2022-12-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDataIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameIndex', models.TextField(default='Data Scraped Index')),
                ('queryIndex', models.IntegerField(default=0)),
                ('modify_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carModel', models.CharField(max_length=500)),
                ('carImage', models.TextField()),
                ('carMileage', models.CharField(max_length=500)),
                ('carRegistration', models.CharField(max_length=500)),
                ('carPower', models.CharField(max_length=500)),
                ('carGearbox', models.CharField(max_length=500)),
                ('carEngine', models.CharField(max_length=500)),
                ('carGears', models.CharField(max_length=500)),
                ('carFuelType', models.CharField(max_length=500)),
                ('carFuelConsumption', models.CharField(max_length=500)),
                ('carEmissions', models.CharField(max_length=500)),
                ('carColor', models.CharField(max_length=500)),
                ('carManColor', models.CharField(max_length=500)),
                ('carBodyType', models.CharField(max_length=500)),
                ('carType', models.CharField(max_length=500)),
                ('carSeats', models.CharField(max_length=500)),
                ('carDoors', models.CharField(max_length=500)),
                ('countryName', models.CharField(max_length=500)),
                ('carOfferNumber', models.CharField(max_length=500)),
                ('carModelCode', models.CharField(max_length=500)),
                ('carPreviousOwner', models.CharField(max_length=500)),
                ('carrEmissionClass', models.CharField(max_length=500)),
                ('carNonSmoker', models.CharField(max_length=500)),
                ('carPrice', models.CharField(max_length=500)),
                ('carVAT', models.CharField(max_length=500)),
                ('carEquipment', models.TextField()),
                ('carContactName', models.CharField(max_length=500)),
                ('carContactNumber', models.CharField(max_length=500)),
                ('carContactAddress', models.CharField(max_length=500)),
                ('carCompanyName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carlinks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DataScrapTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameIndex', models.TextField(default='This time refers to the start and end, the execution time to scrape car detail data')),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LinkScrapTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameIndex', models.TextField(default='This time refers to the start and end, the execution time to scrape car links')),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LinksIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameIndex', models.TextField(default='Car link Scrapped Index')),
                ('yearQueryIndex', models.IntegerField(default=0)),
                ('priceQueryIndex', models.IntegerField(default=0)),
                ('carNameQueryIndex', models.IntegerField(default=0)),
                ('modify_time', models.DateTimeField()),
            ],
        ),
    ]
