# Generated by Django 4.1.3 on 2022-11-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrappingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodeldetail',
            name='carMakeName',
        ),
        migrations.DeleteModel(
            name='CarMake',
        ),
        migrations.DeleteModel(
            name='CarModelDetail',
        ),
    ]
