# Generated by Django 4.1.3 on 2022-12-13 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datascraptime',
            name='endTime',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='datascraptime',
            name='startTime',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AlterField(
            model_name='linkscraptime',
            name='endTime',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='linkscraptime',
            name='startTime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
